<a href="https://colab.research.google.com/github/Prerna99-star/Predicting-Energy-from-power-plant/blob/master/Copy_of_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [0]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values

In [0]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [0]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units = 6, activation= 'relu'))

### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units = 6, activation= 'relu'))

### Adding the output layer

In [0]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [0]:
ann.compile(optimizer='adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [16]:
ann.fit(X_train, y_train, epochs = 100, batch_size=32 )

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 207549.7031
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 5188.8994
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 301.4559
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 237.9947
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 193.2846
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 157.6625
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 130.6964
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 107.4266
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 89.8760
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 75.3851
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 63.6654
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - los

### Predicting the results of the Test set

In [17]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1 ))

[[433.17 431.23]
 [464.24 460.01]
 [467.63 461.14]
 ...
 [474.98 473.26]
 [441.58 438.  ]
 [460.82 463.28]]
